// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodLift.Infrastructure.Repositories;

#nullable disable

namespace MoodLift.Infrastructure.Migrations
{
    [DbContext(typeof(MoodLiftDbContext))]
    [Migration("20260621132531_SavedPlaylists")]
    partial class SavedPlaylists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MoodLift.Core.Entities.MoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CaffeineDrinks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CopingStrategies")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoogleUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MoodScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryEmotion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SleepHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StressScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Symptoms")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleUserId", "CreatedAtUtc");

                    b.ToTable("MoodEntries");
                });

            modelBuilder.Entity("MoodLift.Core.Entities.SavedPlaylist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkplaceUse")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleUserId", "CreatedAtUtc");

                    b.ToTable("SavedPlaylists");
                });
#pragma warning restore 612, 618
        }
    }
}
